[program:laravel-api]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/bed-podscare/apps/api
command=php artisan serve --host=127.0.0.1 --port=8000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/laravel-serve.log
stderr_logfile=/var/log/laravel-serve-err.log
stopwaitsecs=30
